### ISSUE TITLE
add pathauto dependency

### ISSUE THREAD

**Issue by sudishth** [lauriii/subpathauto#4] opened 2016-08-06 11:23 UTC

**Comment by lauriii** [comment] 2016-08-08 02:05
Is there and actual bug that is caused by this? Why should we add pathauto module as a dependency?

**Comment by lauriii** [comment] 2016-09-01 10:40
This module has been moved to Drupal.org. Since you haven't come back on this issue I will close this issue. You can create new issue and reply to my question here: https://www.drupal.org/project/subpathauto

**Closed as completed by lauriii** 2016-09-01 10:40 UTC
